/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rezervasyon.View;
import Helper.Helper;
import Helper.Connections;
import com.mycompany.rezervasyon.View.User;
import com.mycompany.rezervasyon.View.Admin;
import com.mycompany.rezervasyon.View.FindTicket;
import static com.mycompany.rezervasyon.View.aCompanyGUI.comp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Administrator
 */
public class LoginGUI extends javax.swing.JFrame {
    static Company compList;
    private Connections conn = new Connections();
    private int forCompID;
    
    int getforCompID(){return forCompID;}
    void setforCompID(int i){this.forCompID = i;}
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI(Admin userL, Company compL) {
        Admin usertests = userL;
        compList = compL;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabName = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDepPoint = new javax.swing.JComboBox<>();
        jDesPoint = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Yolcusayisi = new javax.swing.JTextField();
        UListAll = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TravelDate = new javax.swing.JComboBox<>();
        UFindTicket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        compButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        compLogin = new javax.swing.JTextField();
        seePass = new javax.swing.JCheckBox();
        compPass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adminLogin = new javax.swing.JTextField();
        adminButton = new javax.swing.JButton();
        adminPass = new javax.swing.JPasswordField();
        seepassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rezervasyon");

        jLabel1.setText("Rezervasyon Uygulamasi");

        jLabel6.setText("Destination Point:");

        jLabel8.setText("Departure point:");

        jDepPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Kocaeli", "Eskisehir", "Konya", "Bilecik", "Ankara" }));

        jDesPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Kocaeli", "Eskisehir", "Konya", "Bilecik", "Ankara" }));
        jDesPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesPointActionPerformed(evt);
            }
        });

        jLabel9.setText("Yolcu Sayısı:");

        Yolcusayisi.setText("   ");

        UListAll.setText("LİST VEHİCLE");
        UListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UListAllActionPerformed(evt);
            }
        });

        jLabel10.setText("Travel Date:");

        TravelDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10" }));
        TravelDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TravelDateActionPerformed(evt);
            }
        });

        UFindTicket.setText("FİND TİCKET");
        UFindTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFindTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(UListAll)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UFindTicket)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TravelDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Yolcusayisi)
                                .addComponent(jDepPoint, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(140, 140, 140))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDepPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDesPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Yolcusayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TravelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UListAll)
                    .addComponent(UFindTicket))
                .addGap(30, 30, 30))
        );

        tabName.addTab("User", jPanel3);

        compButton.setText("login");
        compButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Company Pass");

        jLabel5.setText("Company login");

        compLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compLoginActionPerformed(evt);
            }
        });

        seePass.setText("See Password");
        seePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(compLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(compPass)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(compButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(seePass)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(compLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(compPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(seePass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(compButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tabName.addTab("Company login", jPanel1);

        jLabel2.setText("Admin Login");

        jLabel3.setText("Admin Pass");

        adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginActionPerformed(evt);
            }
        });

        adminButton.setText("login");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        seepassword.setText("See Password");
        seepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seepasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(adminPass))))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seepassword)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seepassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tabName.addTab("Admin login", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabName)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(tabName, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLoginActionPerformed

    private void compLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compLoginActionPerformed
       
        
    }//GEN-LAST:event_compLoginActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        
        if(!("admin".equals(adminLogin.getText()) && ("admin".equals(adminPass.getText()))))
        {
            Helper.showMsg("wrong");
        }
        else
        {
            
            try {
                Connection con = conn.connDB();
                Statement st;
                st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM company");
                LoginGUI asd = this;
                while(rs.next()) {
                    AdminGUI admingui = new AdminGUI(); 
                    compList.fillAdminGui(rs, admingui);
                    admingui.setVisible(true);
                    dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            
            
        }
    }//GEN-LAST:event_adminButtonActionPerformed

        
    private void compButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compButtonActionPerformed
            try {
                int flag = 1;
                Connection con = conn.connDB();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM company");
                LoginGUI asd = this;
                while(rs.next()) {
                    if (compLogin.getText().equals(rs.getString("CompName")) && 
                            compPass.getText().equals(rs.getString("CompPass"))) 
                    {
                        Company zx = compList.fillComp(rs, compLogin.getText()); 
                        flag = 0;                     
                        asd.setforCompID(rs.getInt("id"));
                    } 
                }
                if (flag == 0) {
                        rs = st.executeQuery("SELECT * FROM company");
                        aCompanyGUI acompgui = new aCompanyGUI(asd, compList); 
                        compList.fillCompGui(rs, compLogin.getText(), acompgui);
                        acompgui.setVisible(true);
                        dispose();
                }
                else {
                    Helper.showMsg("wrong");
                    flag = 1;
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_compButtonActionPerformed

    private void seepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seepasswordActionPerformed
        if(seepassword.isSelected())
        {
            adminPass.setEchoChar((char)0);
        }
        else
        {
            adminPass.setEchoChar('*');
        }
    }//GEN-LAST:event_seepasswordActionPerformed

    private void seePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePassActionPerformed
         if(seePass.isSelected())
        {
            compPass.setEchoChar((char)0);
        }
        else
        {
            compPass.setEchoChar('*');
        }
    }//GEN-LAST:event_seePassActionPerformed

    private void UListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UListAllActionPerformed
        ListVehicle lstVhc = new ListVehicle();
        DefaultTableModel tblModel = (DefaultTableModel) lstVhc.gettable2List().getModel();
        tblModel.setRowCount(0);
        try {
            Connection con = conn.connDB();
            Statement st = con.createStatement();      
            ResultSet rs = st.executeQuery("SELECT * FROM company");
            while(rs.next()) {   
                    Vector<Object> rod = new Vector<>();
                    rod.add(rs.getString("CompName"));
                    rod.add(rs.getString("VehicleName"));
                    rod.add(rs.getString("SeatNumber"));
                    rod.add(rs.getString("SeferNo"));
                    tblModel.addRow(rod);
            }
            lstVhc.gettable2List().setModel(tblModel);
            lstVhc.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            SQLException name = ex;
        }
        
        
        
        
    }//GEN-LAST:event_UListAllActionPerformed

    private void UFindTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFindTicketActionPerformed
        //TODO add your handling code here: find ticket
        String jDep = jDepPoint.getSelectedItem().toString();
        String jDes = jDesPoint.getSelectedItem().toString();
        FindTicket findtckt = new FindTicket(TravelDate.getSelectedItem().toString());
        DefaultTableModel tblModel = (DefaultTableModel) findtckt.gettable2Find().getModel();
        tblModel.setRowCount(0);
        try {
            Connection con = conn.connDB();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM company");
            Statement stSeferNot = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rsSeferNot = stSeferNot.executeQuery("SELECT * FROM sefernot");
            while (rs.next()) {
                Company comp = compList.fillComp2(rs);
     
                while (rsSeferNot.next()) {
                    int seferNotExpeditionNo = rsSeferNot.getInt("seferNo");
                    int companyExpeditionNo = comp.getExpeditionNo();
                    if (seferNotExpeditionNo == companyExpeditionNo) {
                        int selectednum = rsSeferNot.getInt(jDep);
                        if (selectednum == 1)
                        {
                            int selectednums = rsSeferNot.getInt(jDes);
                            if(selectednums == 1 && !(jDep.equals(jDes))) {
                                Vector<Object> rod = new Vector<>();
                                rod.add(rs.getString("CompName"));
                                rod.add(rs.getString("VehicleName"));
                                rod.add(rs.getString("SeatNumber"));
                                rod.add(rs.getString("SeferNo"));
                                tblModel.addRow(rod);
                            }
                        }
                      
                    }
                }
                rsSeferNot.beforeFirst();
            }
            findtckt.gettable2Find().setModel(tblModel);
            findtckt.setVisible(true);
            dispose();
      
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_UFindTicketActionPerformed

    private void jDesPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDesPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesPointActionPerformed

    private void TravelDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TravelDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TravelDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin usertests = null;
                
                new LoginGUI(usertests, compList).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TravelDate;
    private javax.swing.JButton UFindTicket;
    private javax.swing.JButton UListAll;
    private javax.swing.JTextField Yolcusayisi;
    private javax.swing.JButton adminButton;
    private javax.swing.JTextField adminLogin;
    private javax.swing.JPasswordField adminPass;
    private javax.swing.JButton compButton;
    private javax.swing.JTextField compLogin;
    private javax.swing.JPasswordField compPass;
    private javax.swing.JComboBox<String> jDepPoint;
    private javax.swing.JComboBox<String> jDesPoint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox seePass;
    private javax.swing.JCheckBox seepassword;
    private javax.swing.JTabbedPane tabName;
    // End of variables declaration//GEN-END:variables
}
